sonar.projectKey=bobanboshevski_rirs-mag-vaje
sonar.organization=bobanboshevski
sonar.host.url=https://sonarcloud.io

# Analyze frontend and backend
sonar.sources= management-express-backend, frontend  # .
# Analyze only frontend
# sonar.sources=frontend

# Exclusions
sonar.exclusions=**/node_modules/**,**/.next/**,**/dist/**

# Coverage (Jest) - kako naredim da imam za frontend in backend
sonar.javascript.lcov.reportPaths= frontend.lcov.info,backend.lcov.info
# frontend/coverage/lcov.info,management-express-backend/coverage/lcov.info