const getGuests = (req, res) => {

    const guests = [{
        id: "guest_001",
        firstName: "Sophie",
        lastName: "Laurent",
        email: "sophie.laurent@email.com",
        phone: "+33 6 12 34 56 78",
        nationality: "France",
        countryCode: "FR",
        dateOfBirth: "1988-05-15",
        totalBookings: 3,
        totalSpent: 1575,
        totalNights: 15,
        averageStayLength: 5,
        firstBookingDate: "2024-03-10T00:00:00Z",
        lastBookingDate: "2025-10-15T00:00:00Z",
        preferredApartmentTypes: ["Lakeview Apartment"],
        bookingChannel: "booking.com",
        averageBookingLeadTime: 45,
        vipStatus: true,
        guestRating: 5,
        status: "active",
        marketingOptIn: true,
        preferredLanguage: "French",
        notes: "Excellent guest, always leaves apartments in perfect condition",
        tags: ["VIP", "Returning", "Clean"],
    }, {
        id: "guest_002",
        firstName: "Marco",
        lastName: "Rossi",
        email: "marco.rossi@email.it",
        phone: "+39 328 1234567",
        nationality: "Italy",
        countryCode: "IT",
        dateOfBirth: "1992-08-22",
        totalBookings: 2,
        totalSpent: 1450,
        totalNights: 14,
        averageStayLength: 7,
        firstBookingDate: "2024-06-20T00:00:00Z",
        lastBookingDate: "2025-10-18T00:00:00Z",
        preferredApartmentTypes: ["Central City Loft"],
        bookingChannel: "website",
        averageBookingLeadTime: 30,
        vipStatus: false,
        guestRating: 5,
        status: "active",
        marketingOptIn: true,
        preferredLanguage: "Italian",
        notes: "Business traveler, prefers quiet apartments",
        tags: ["Business", "Returning"],
    }, {
        id: "guest_003",
        firstName: "Anna",
        lastName: "Kowalski",
        email: "anna.k@email.pl",
        phone: "+48 123 456 789",
        nationality: "Poland",
        countryCode: "PL",
        dateOfBirth: "1995-12-03",
        totalBookings: 1,
        totalSpent: 250,
        totalNights: 3,
        averageStayLength: 3,
        firstBookingDate: "2025-10-22T00:00:00Z",
        lastBookingDate: "2025-10-22T00:00:00Z",
        preferredApartmentTypes: ["Sunset Studio"],
        bookingChannel: "airbnb",
        averageBookingLeadTime: 12,
        vipStatus: false,
        guestRating: 4,
        status: "active",
        marketingOptIn: false,
        preferredLanguage: "Polish",
        tags: ["New"],
    }, {
        id: "guest_004",
        firstName: "David",
        lastName: "Chen",
        email: "david.chen@email.com",
        phone: "+1 415 555 0100",
        nationality: "United States",
        countryCode: "US",
        dateOfBirth: "1985-03-18",
        totalBookings: 4,
        totalSpent: 2800,
        totalNights: 28,
        averageStayLength: 7,
        firstBookingDate: "2023-08-15T00:00:00Z",
        lastBookingDate: "2025-11-01T00:00:00Z",
        preferredApartmentTypes: ["Garden View Suite", "Mountain View Retreat"],
        bookingChannel: "direct",
        averageBookingLeadTime: 60,
        vipStatus: true,
        guestRating: 5,
        status: "active",
        marketingOptIn: true,
        preferredLanguage: "English",
        notes: "Loyal customer, always books for holidays",
        tags: ["VIP", "Loyal", "Holiday"],
    }, {
        id: "guest_005",
        firstName: "Lisa",
        lastName: "Anderson",
        email: "lisa.anderson@email.com",
        phone: "+1 206 555 0147",
        nationality: "United States",
        countryCode: "US",
        dateOfBirth: "1990-07-25",
        totalBookings: 2,
        totalSpent: 720,
        totalNights: 6,
        averageStayLength: 3,
        firstBookingDate: "2024-12-10T00:00:00Z",
        lastBookingDate: "2025-10-20T00:00:00Z",
        preferredApartmentTypes: ["Mountain View Retreat"],
        bookingChannel: "booking.com",
        averageBookingLeadTime: 20,
        vipStatus: false,
        guestRating: 4,
        status: "active",
        marketingOptIn: true,
        preferredLanguage: "English",
        tags: ["Family"],
    }, {
        id: "guest_006",
        firstName: "Hans",
        lastName: "Müller",
        email: "hans.muller@email.de",
        phone: "+49 151 1234567",
        nationality: "Germany",
        countryCode: "DE",
        dateOfBirth: "1978-11-08",
        totalBookings: 5,
        totalSpent: 3250,
        totalNights: 30,
        averageStayLength: 6,
        firstBookingDate: "2023-05-20T00:00:00Z",
        lastBookingDate: "2025-09-10T00:00:00Z",
        preferredApartmentTypes: ["Lakeview Apartment", "Central City Loft"],
        bookingChannel: "website",
        averageBookingLeadTime: 90,
        vipStatus: true,
        guestRating: 5,
        status: "active",
        marketingOptIn: true,
        preferredLanguage: "German",
        notes: "Plans trips far in advance, very organized",
        tags: ["VIP", "Loyal", "Planner"],
    },];

    res.json(guests);
}

module.exports = {getGuests};