name: Backend CI
on:
  push:
    branches: [ master, pre-production, production ]
  pull_request:
    branches: [ master, pre-production, production ]

jobs:
  build-backend:
    name: Build Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Cache node modules (dependencies)
        uses: actions/cache@v4
        with:
          path: management-express-backend/node_modules
          key: ${{ runner.os }}-backend-node-${{ hashFiles('management-express-backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-node-
        # ⚠️ Caching:
        # - Če cache obstaja (cache hit), se node_modules obnovi, preden se zažene npm install.
        # - Če cache ne obstaja (cache miss), npm install ponovno ustvari mapo node_modules.
        # TODO: I NEED EXPLANATION FOR THIS


      - name: Install backend dependencies
        working-directory: management-express-backend
        run: npm install #ci

#      - name: Build backend
#        working-directory: management-express-backend
#        run: npm run build

      - name: Upload backend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-build
#          path: management-express-backend/build/
          # upload source code - we don't need to build because Node can run js files directly
          path: |
            management-express-backend/
            management-express-backend/node_modules/

  test-backend:
    name: Test Backend
    needs: build-backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Cache node modules (dependencies) # caching backend dependencies
        uses: actions/cache@v4
        with:
          path: management-express-backend/node_modules
          key: ${{ runner.os }}-backend-node-${{ hashFiles('management-express-backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-backend-node-

      - name: Install backend dependencies
        working-directory: management-express-backend
        run: npm install
        # ⚠️ Cache hit:
        # - Če je cache hit, npm install preveri obstoječe odvisnosti in ne namešča ničesar dodatnega.
        # - Če je cache miss, npm install ponovno ustvari mapo node_modules.

      - name : Run backend tests
        working-directory: management-express-backend
        run: npm run test:coverage # -- --coverage

      - name: Upload backend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: management-express-backend/coverage/

        
        
        
        
        
        
