name: Frontend CI
on:
  push:
    branches: [ master, pre-production, production ]
  pull_request:
    branches: [ master, pre-production, production ]

jobs:
  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: { node-version: '20' }

        # TODO: CHECK THE MEANING OF THIS
        # We dont cache the ~/.npm ? ?
      - name: Cache node modules (dependencies)
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-node- # fallback mechanism to pick the closest match

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci #ci # npm install --ignore-scripts
        # ci don't just remove the node_modules folder and installs the dependencies again??
        # What's the point that we cache that.

      - name: Build frontend
        #        run: |
        #          cd frontend
        #          npm run build
        working-directory: frontend
        run: npm run build

      - name: List frontend directory (debug)
        run: ls -la frontend/

      - name: Rename .next to next-build (workaround for hidden dir)
        run: mv frontend/.next frontend/next-build

      - name: Upload frontend build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: frontend/next-build
          if-no-files-found: error

  test-frontend:
    name: Test Frontend
    needs: build-frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Cache node modules (dependencies)
        uses: actions/cache@v4
        with:
          path: frontend/node_modules
          key: ${{ runner.os }}-frontend-node-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-frontend-node-

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install #ci

      - name: Run frontend tests
        working-directory: frontend
        run: npm run test -- --coverage --watchAll=false

      - name: Upload frontend coverage report
        uses: actions/upload-artifact@v4
        with:
          path: frontend/coverage/
          name: frontend-coverage

  docker-build-push:
    name: Build and push Docker image to Development
    needs: test-frontend
    runs-on: ubuntu-latest
    environment: Development
    if: github.ref == 'refs/heads/master' # runs only on master branch when push event is triggered

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx for caching
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/rirs-frontend:dev
            ${{ secrets.DOCKER_USERNAME }}/rirs-frontend:${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.BACKEND_API_URL }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/rirs-frontend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/rirs-frontend:buildcache,mode=max

          #      - name: Build Docker image
          #        #        uses: docker/build-push-action@v3
          #        run: |
          #          docker build --build-arg NEXT_PUBLIC_API_URL=${{ secrets.BACKEND_API_URL }} -t ${{ secrets.DOCKER_USERNAME }}/rirs-frontend:dev ./frontend
          #          docker tag ${{ secrets.DOCKER_USERNAME }}/rirs-frontend:dev ${{ secrets.DOCKER_USERNAME }}/rirs-frontend:${{ github.sha }}
          #      #          -t ${{ secrets.DOCKER_USERNAME }}/frontend-app:${{ github.ref_name }}
          #
          #      - name: Push Docker image to DockerHub
          #        run: |
          #          docker push ${{ secrets.DOCKER_USERNAME }}/rirs-frontend:dev
          #          docker push ${{ secrets.DOCKER_USERNAME }}/rirs-frontend:${{ github.sha }}



  deploy-to-render:
    name: Deploy to Render Development
    needs: docker-build-push
    runs-on: ubuntu-latest
    environment: Development
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Deploy to Render
        run: |
          curl -X POST ${{ secrets.RENDER_FRONTEND_DEPLOY_HOOK_URL }}

  sonar-cloud-analysis:
    needs: test-frontend
    runs-on: ubuntu-latest
    #    environment: Development
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/production'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm ci

      - name: Upload frontend coverage report
        run: |
          cp frontend/coverage/lcov.info .

      - name: Run SonarCloud Scan analysis
        uses: sonarsource/sonarcloud-github-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

        # QUALITY GATE CHECK
      - name: SonarCloud Quality Gate Check
        uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  docker-build-push-prod:
    name: Build and push Docker image to Production
    needs: [ test-frontend, sonar-cloud-analysis ]
    runs-on: ubuntu-latest
    environment: Production
    if: github.ref == 'refs/heads/production'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx for caching
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image with Docker Buildx (caching)
        uses: docker/build-push-action@v3
        with:
          context: frontend
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/rirs-frontend:prod
            ${{ secrets.DOCKER_USERNAME }}/rirs-frontend:${{ github.sha }}
          build-args: |
            NEXT_PUBLIC_API_URL=${{ secrets.BACKEND_API_URL }}
          # it takes the build-args from the Production environment
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/rirs-frontend:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/rirs-frontend:buildcache,mode=max

  deploy-to-render-prod:
    name: Deploy to Render Production
    needs: docker-build-push-prod
    runs-on: ubuntu-latest
    environment: Production
    if: github.ref == 'refs/heads/production'

    steps:
      - name: Deploy to Render Production
        run: |
          curl -X POST ${{ secrets.RENDER_PRODUCTION_FRONTEND_DEPLOY_HOOK_URL }}

  # GitHub pages
  deploy-pages:
    name: Deploy to GitHub Pages
    needs: test-frontend
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    #    if: github.ref == 'refs/heads/master'
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs